export enum ProductType {
  JEWELRY = 'JEWELRY',
  CLOTHING = 'CLOTHING',
  ACCESSORIES = 'ACCESSORIES',
  HOME_DECOR = 'HOME_DECOR',
  ART = 'ART',
  CERAMICS = 'CERAMICS',
  WOODWORK = 'WOODWORK',
  CANDLES = 'CANDLES',
  COSMETICS = 'COSMETICS',
  TOYS = 'TOYS'
}
