--liquibase formatted sql

--changeset fmi:003-create-reviews-table

CREATE TABLE reviews
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    VARCHAR(50)                             NOT NULL,
    product_id BIGINT                                  NOT NULL,
    text       TEXT,
    rating     INT                                     NOT NULL,

    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT fk_reviews_on_user FOREIGN KEY (user_id) REFERENCES users (username),
    CONSTRAINT fk_reviews_on_product FOREIGN KEY (product_id) REFERENCES products (id)
);

--rollback DROP TABLE reviews;
