--liquibase formatted sql

--changeset fmi:004-create-carts-table

CREATE TABLE carts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR(50)                             NOT NULL,

    CONSTRAINT pk_carts PRIMARY KEY (id),
    CONSTRAINT uq_carts_user UNIQUE (user_id),
    CONSTRAINT fk_carts_on_user FOREIGN KEY (user_id) REFERENCES users (username)
);

--rollback DROP TABLE carts;
