--liquibase formatted sql

--changeset fmi:005-create-cart-items-table

CREATE TABLE cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INT                                     NOT NULL,

    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_cart_items_on_cart FOREIGN KEY (cart_id) REFERENCES carts (id),
    CONSTRAINT fk_cart_items_on_product FOREIGN KEY (product_id) REFERENCES products (id)
);

--rollback DROP TABLE cart_items;
