--liquibase formatted sql

--changeset fmi:007-create-order-items-table

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INT                                     NOT NULL,
    price      BIGINT                                  NOT NULL,

    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_on_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_on_product FOREIGN KEY (product_id) REFERENCES products (id)
);

--rollback DROP TABLE order_items;
