--liquibase formatted sql

--changeset fmi:008-create-events-table

CREATE TABLE events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    description    TEXT,
    type           VARCHAR(50)                             NOT NULL,
    user_id        VARCHAR(50)                             NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE,
    end_date       TIMESTAMP WITHOUT TIME ZONE,
    is_active      BOOLEAN                                 NOT NULL DEFAULT FALSE,
    content        TEXT,
    discount_type  VARCHAR(50),
    discount_value BIGINT,
    location       VARCHAR(255),

    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_on_user FOREIGN KEY (user_id) REFERENCES users (username)
);

--rollback DROP TABLE events;
