--liquibase formatted sql

--changeset fmi:001-create-product-table

CREATE TABLE products
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_type VARCHAR(50)                             NOT NULL,
    name         VARCHAR(100)                            NOT NULL DEFAULT 'Unnamed Product',
    description  TEXT,
    price        BIGINT                                  NOT NULL,
    quantity     INT                                     NOT NULL,
    user_id      VARCHAR(50)                             NOT NULL,

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_on_user FOREIGN KEY (user_id) REFERENCES users (username)
);

--rollback DROP TABLE show;