--liquibase formatted sql

--changeset fmi:006-create-orders-table

CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        VARCHAR(50)                             NOT NULL,
    currency       VARCHAR(10)                             NOT NULL,
    total_amount   BIGINT                                  NOT NULL,
    status         VARCHAR(50)                             NOT NULL,

    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_on_user FOREIGN KEY (user_id) REFERENCES users (username)
);

--rollback DROP TABLE orders;
