--liquibase formatted sql

--changeset fmi:010-create-payments-table

CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       BIGINT                                  NOT NULL,
    amount         BIGINT                                  NOT NULL,
    currency       VARCHAR(50)                             NOT NULL,
    payment_method VARCHAR(50)                             NOT NULL,
    paid_at        TIMESTAMP                               NOT NULL,

    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT fk_payments_on_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

--rollback DROP TABLE payments;
