server:
  port: 9090
spring:
  config:
    activate:
      on-profile: dev

marketplace:
  log-level: DEBUG
  log-file: logs/marketplace-dev.log

# is it okay this -  bg.sofia.uni.fmi.localmarketplace ???
logging:
  level:
    root: INFO
    bg.sofia.uni.fmi.localmarketplace: DEBUG
