spring:
  config:
    activate:
      on-profile: prod

marketplace:
  log-level: INFO
  log-file: logs/marketplace-prod.log

# is it okay this -  bg.sofia.uni.fmi.localmarketplace ???
logging:
  level:
    root: WARN
    bg.sofia.uni.fmi.localmarketplace: INFO
